---
title: "SANGER ANALYSIS REPORT"
subtitle: "Complete analysis report on CRSIPR edited reads after Sanger sequencing, using ICE and R statistical analysis."
date: now
format: 
  html: 
    title-block-banner: true
    title-block-style: default
    toc: true
    toc-depth: 2
    toc-title: "Contents"
    toc-location: left
    theme:
      light: minty
      dark: darkly
    embed-resources: true
    df-print: kable
    code-links: 
    - text: CRISPR Analysis Repo
      icon: github
      href: https://github.com/Akschya/CRISPR_Analysis 
editor: visual
---


```{r setup, include=FALSE}
#| label: R environment setup

#### R ENV SETUP ####
options(repos = c(
  binary = "https://packagemanager.rstudio.com/all/__linux__/focal/latest",
  source = "https://packagemanager.rstudio.com/all/latest",
  CRAN = "https://cloud.r-project.org",
  djnavarro = "https://djnavarro.r-universe.dev",
  Bioconductor = "https://bioconductor.org/packages/release/bioc"
))

# Load the yaml package to read YAML files
if (!require(yaml)) {
  install.packages("yaml")
  library(yaml)
}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
    library(BiocManager)

install_packages <- function(file = "packages.yml") {
  # Read the YAML file
  packages <- yaml::read_yaml(file)
  
  # Check if the 'packages' key exists
  if (!is.list(packages) || is.null(packages$packages)) {
    stop("Invalid structure in YAML file. Expected a top-level 'packages' key.")
  }
  
  # Extract sections (base and bioconductor) if they exist
  base_pkgs <- packages$packages$base
  bioconductor_pkgs <- packages$packages$bioconductor
  
  # Install base packages
  if (!is.null(base_pkgs) && length(base_pkgs) > 0) {
    for (pkg in base_pkgs) {
      if (!requireNamespace(pkg, quietly = TRUE)) {
        install.packages(pkg)
      }
    }
  }
  
  # Install Bioconductor packages
  if (!is.null(bioconductor_pkgs) && length(bioconductor_pkgs) > 0) {
    bioc_pkgs <- BiocManager::available()
    for (pkg in bioconductor_pkgs) {
      if (pkg %in% bioc_pkgs && !requireNamespace(pkg, quietly = TRUE)) {
        BiocManager::install(pkg, ask = FALSE)
      }
    }
  }
}
```

# Sequence Metrics

```{r load libraries}
# Load necessary libraries
library(sangerseqR)
library(dplyr)
library(ggplot2)
library(Biostrings)


```

# Session Info

```{r, echo=FALSE}
sessionInfo()
```
